MAP_LAYOUT = [
    "WWWWWWWWWWWWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGW",
    "WGGIGGGWWWWGGGGGGGGW",
    "WGGGEGGWGGWBGGGGGGGW",
    "WGGGGGGWGGWGGGGGEGGW",
    "WGGGGBGWGGWGGGGGGGGW",
    "WGGGGGGWWWWGGGGGGGGW",
    "WGGGGGGGGGGGGGGGGGGW",
    "WWWWWWWWWWWWWWWWWWWW",
]
